kind: pipeline
name: x86_64

volumes:
- name: debian-package-cache
  host:
    path: /var/cache/debian-package-cache

trigger:
  event:
    exclude:
    - tag

steps:
- name: download
  image: plugins/download
  settings:
    source: https://raw.githubusercontent.com/badaix/popl/v1.2.0/include/popl.hpp
    destination: src/popl.hpp

- name: gcc5
  image: debian:stretch-slim
  pull: always
  environment:
    LANG: C.utf8
    CXX: g++-5
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - apt-get update -q
  - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
  - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list.d/ubuntu-toolchain-r.list
  - apt-get install -qy gnupg
  - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x60c317803a41ba51845e371a1e9377a2ba9ef27f
  - gpg --armor --export 0x60c317803a41ba51845e371a1e9377a2ba9ef27f | apt-key add -
  - apt-get update -q
  - apt-get install -qy -t xenial g++-5
  - apt-get install -qy cmake pkg-config
  - apt-get install -qy libcurl4-openssl-dev libxdg-basedir-dev libvsqlitepp-dev libboost-system-dev libboost-filesystem-dev asciidoc catch
  - apt-get install -qy -t sid libcurlpp-dev
  - rm -rf build && mkdir -p build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make VERBOSE=1
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: gcc6
  image: debian:stretch-slim
  pull: always
  environment:
    LANG: C.utf8
    CXX: g++-6
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
  - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
  - apt-get update -q
  - apt-get install -qy g++-6 cmake pkg-config
  - apt-get install -qy libcurl4-openssl-dev libxdg-basedir-dev libvsqlitepp-dev libboost-system-dev libboost-filesystem-dev asciidoc catch
  - apt-get install -qy -t sid libcurlpp-dev
  - rm -rf build && mkdir -p build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_TESTS=YES ..
  - make VERBOSE=1
  - ctest
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: gcc7
  image: debian:stretch-slim
  pull: always
  environment:
    LANG: C.utf8
    CXX: g++-7
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - apt-get update -q
  - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
  - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list.d/ubuntu-toolchain-r.list
  - apt-get install -qy gnupg
  - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x60c317803a41ba51845e371a1e9377a2ba9ef27f
  - gpg --armor --export 0x60c317803a41ba51845e371a1e9377a2ba9ef27f | apt-key add -
  - apt-get update -q
  - apt-get install -qy -t xenial g++-7
  - apt-get install -qy cmake pkg-config
  - apt-get install -qy libcurl4-openssl-dev libxdg-basedir-dev libvsqlitepp-dev libboost-system-dev libboost-filesystem-dev asciidoc catch
  - apt-get install -qy -t sid libcurlpp-dev
  - rm -rf build && mkdir -p build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make VERBOSE=1
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: gcc8
  image: debian:stretch-slim
  pull: always
  environment:
    LANG: C.utf8
    CXX: g++-8
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - apt-get update -q
  - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
  - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu xenial main" >> /etc/apt/sources.list.d/ubuntu-toolchain-r.list
  - apt-get install -qy gnupg
  - gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys 0x60c317803a41ba51845e371a1e9377a2ba9ef27f
  - gpg --armor --export 0x60c317803a41ba51845e371a1e9377a2ba9ef27f | apt-key add -
  - apt-get update -q
  - apt-get install -qy -t xenial g++-8
  - apt-get install -qy cmake pkg-config
  - apt-get install -qy libcurl4-openssl-dev libxdg-basedir-dev libvsqlitepp-dev libboost-system-dev libboost-filesystem-dev asciidoc catch
  - apt-get install -qy -t sid libcurlpp-dev
  - rm -rf build && mkdir -p build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make VERBOSE=1
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: clang3
  image: debian:stretch-slim
  pull: always
  environment:
    LANG: C.utf8
    CXX: clang++
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
  - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
  - apt-get update -q
  - apt-get install -qy clang cmake pkg-config
  - apt-get install -qy libcurl4-openssl-dev libxdg-basedir-dev libvsqlitepp-dev libboost-system-dev libboost-filesystem-dev asciidoc catch
  - apt-get install -qy -t sid libcurlpp-dev
  - rm -rf build && mkdir -p build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make VERBOSE=1
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: clang5
  image: debian:stretch-slim
  pull: always
  environment:
    LANG: C.utf8
    CXX: clang++-5.0
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
  - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
  - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/stretch.list
  - apt-get update -q
  - apt-get install -qy -t stretch-backports clang-5.0
  - apt-get install -qy cmake pkg-config
  - apt-get install -qy libcurl4-openssl-dev libxdg-basedir-dev libvsqlitepp-dev libboost-system-dev libboost-filesystem-dev asciidoc catch
  - apt-get install -qy -t sid libcurlpp-dev
  - rm -rf build && mkdir -p build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make VERBOSE=1
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: clang6
  image: debian:stretch-slim
  pull: always
  environment:
    LANG: C.utf8
    CXX: clang++-6.0
    CXXFLAGS: -pipe -O2
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
  - echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
  - echo "deb http://deb.debian.org/debian stretch-backports main" >> /etc/apt/sources.list.d/stretch.list
  - apt-get update -q
  - apt-get install -qy -t stretch-backports clang-6.0
  - apt-get install -qy cmake pkg-config
  - apt-get install -qy libcurl4-openssl-dev libxdg-basedir-dev libvsqlitepp-dev libboost-system-dev libboost-filesystem-dev asciidoc catch
  - apt-get install -qy -t sid libcurlpp-dev
  - rm -rf build && mkdir -p build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make VERBOSE=1
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: notify
  image: drillster/drone-email
  pull: always
  settings:
    host: cryptoparty-celle.de
    from: drone@tzend.de
    username:
      from_secret: email_username
    password:
      from_secret: email_password
  when:
    status: [ changed, failure ]
