= remwharead

*remwharead* saves URIs of things you want to remember in a database along with
 an URI to the archived version, the current date and time, title, description,
 the full text of the page and optional tags.

== Usage

See https://schlomp.space/tastytea/remwharead/src/branch/main/remwharead.1.adoc[manpage].

== Install

=== Gentoo

Add my https://schlomp.space/tastytea/overlay[repository] and install it from
there.

[source,zsh]
----
eselect repository enable tastytea
echo "www-misc/remwharead ~amd64" >> /etc/portage/package.accept_keywords/remwharead
emaint sync -r tastytea
emerge -a www-misc/remwharead
----

=== From source

==== Dependencies

* Tested OS: Linux
* C++ compiler (tested: https://gcc.gnu.org/[gcc] 5/6/7/8,
  https://llvm.org/[clang] 3/5/6)
* https://cmake.org/[cmake] (at least: 3.2)
* https://pkgconfig.freedesktop.org/wiki/[pkgconfig] (tested: 0.29)
* http://repo.or.cz/w/libxdg-basedir.git[libxdg-basedir] (tested: 1.2)
* http://vsqlite.virtuosic-bytes.com/[vsqlite++] (tested: 0.3)
* https://github.com/badaix/popl[popl] (tested: 1.2)
* Optional:
** Manpage: http://asciidoc.org/[asciidoc] (tested: 8.6)
** Tests: https://github.com/catchorg/Catch2[catch] (tested: 2.5 / 1.2)

.Install dependencies in Debian stretch.
====
[source,zsh]
----
echo "APT::Default-Release \"stretch\";" >> /etc/apt/apt.conf.d/00default_release
echo "deb http://deb.debian.org/debian sid main" >> /etc/apt/sources.list.d/sid.list
apt-get update
apt-get install g++-6 cmake pkg-config libcurl4-openssl-dev libxdg-basedir-dev \
    libvsqlitepp-dev libboost-system-dev libboost-filesystem-dev asciidoc
apt-get install -t sid libcurlpp-dev
wget -O src/popl.hpp https://raw.githubusercontent.com/badaix/popl/v1.2.0/include/popl.hpp
CXX="g++-6"
----
====

==== Get sourcecode

===== Releases

Download the current release at
https://schlomp.space/tastytea/remwharead/releases[schlomp.space].

===== Development version

[source,zsh]
----
git clone https://schlomp.space/tastytea/remwharead.git
----

==== Compile

[source,zsh]
----
mkdir build
cd build/
cmake ..
cmake --build .
----

.cmake options:
* `-DCMAKE_BUILD_TYPE=Debug` for a debug build.
* `-DWITH_MAN=NO` to not compile the manpage.
* `WITH_TESTS=YES` to compile the tests.

You can run the tests with `ctest` inside the build directory. Install with
`make install`.

== Copyright

----
Copyright © 2019 tastytea <tastytea@tastytea.de>.
License GPLv3: GNU GPL version 3 <https://www.gnu.org/licenses/gpl-3.0.html>.
This program comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
----
