= remwharead(1)
:doctype:       manpage
:Author:        tastytea
:Email:         tastytea@tastytea.de
:Date:          2019-05-11
:Revision:      0.0.0
:man source:    remwharead
:man version:   {revision}
:man manual:    General Commands Manual

== NAME

remwharead - Remember what you read, and when

== SYNOPSIS

*remwharead* [*-t* _tags_] _URL_

*remwhared* *-e* _format_ [*-f* _file_] [*-s* _start_,_end_]

== DESCRIPTION

*remwhared* saves URLs of things you read in a database along with the current
 date and time, title, description, the full text of the page and optional tags.

== OPTIONS

*-t* _tags_, *--tags*=_tags_::
Add tags to _URL_, delimited by commas.

*-e* _format_, *--export*=_format_::
Export to _format_. Possible values are _csv_ and _asciidoc_.

*-f* _file_, *--file*=_file_::
Save output to _file_. Default is stdout.

*-s* _start_,_end_, *--span*=_start_,_end_::
Only export entries between _start_ and _end_. _start_ and _end_ are date and
time representations according to ISO 8601.

*--version*::
Print version, copyright and license.

== EXAMPLES

`remwhared -t tag1,tag2 https://example.com/article.html`

`remwhared -e asciidoc -f out.adoc -s 2019-04-01,2019-05-31`

`remwhared -e asciidoc | asciidoctor --backend=html5 --out-file=out.html -`

== FILES

* *Database*: `${XDG_DATA_HOME}/remwharead.sqlite`

`${XDG_DATA_HOME}` is usually `~/.local/share`.

== REPORTING BUGS

Bugtracker: https://schlomp.space/tastytea/remwharead/issues

E-mail: tastytea@tastytea.de
