= remwharead(1)
:doctype:       manpage
:Author:        tastytea
:Email:         tastytea@tastytea.de
:Date:          2019-05-16
:Revision:      0.0.0
:man source:    remwharead
:man manual:    General Commands Manual

== NAME

remwharead - Remember what you read, and when

== SYNOPSIS

*remwharead* [*-t* _tags_] _URL_

*remwharead* *-e* _format_ [*-f* _file_] [*-s* _start_,_end_]

== DESCRIPTION

*remwharead* saves URLs of things you read in a database along with an URL to
 the archived version, the current date and time, title, description, the full
 text of the page and optional tags.

== OPTIONS

*-t* _tags_, *--tags* _tags_::
Add tags to _URL_, delimited by commas.

*-e* _format_, *--export* _format_::
Export to _format_. Possible values are _csv_ and _asciidoc_. See _FORMATS_.

*-f* _file_, *--file* _file_::
Save output to _file_. Default is stdout.

*-s* _start_,_end_, *--span* _start_,_end_::
Only export entries between and including _start_ and _end_. _start_ and _end_
are date and time representations according to ISO 8601. Time zones are ignored
at the moment. Example: `--span 2019-01-01,2019-02-10T12:30`.

*-S* _attribute_, *--sort* _attribute_::
Sort by _time_, _tag_ or _both_ (default) when exporting to _asciidoc_.

*-h*, *--help*::
Show help message.

*-V*, *--version*::
Print version, copyright and license.

== EXAMPLES

`remwharead -t tag1,tag2 https://example.com/article.html`

`remwharead -e asciidoc -f out.adoc -s 2019-04-01,2019-05-31`

`remwharead -e asciidoc | asciidoctor --backend=html5 --out-file=out.html -`

== FORMATS

=== CSV

CSV is short for comma separated values. All fields are quoted and delimited by
commas. Line breaks in the full text are converted to "\n". Our CSV
implementation follows RFC 4180 and the full MIME media type is
`text/csv;charset=utf-8;header=present`.

== FILES

* *Database*: `${XDG_DATA_HOME}/remwharead/database.sqlite`

`${XDG_DATA_HOME}` is usually `~/.local/share`.

== REPORTING BUGS

Bugtracker: https://schlomp.space/tastytea/remwharead/issues

E-mail: tastytea@tastytea.de
