= remwharead(1)
:doctype:       manpage
:Author:        tastytea
:Email:         tastytea@tastytea.de
:Date:          2019-05-19
:Revision:      0.0.0
:man source:    remwharead
:man manual:    General Commands Manual

== NAME

remwharead - Saves URIs of things you want to remember in a database

== SYNOPSIS

*remwharead* [*-t* _tags_] _URI_

*remwharead* *-e* _format_ [*-f* _file_] [*-S* _start_,_end_] [[*-s*|*--search-all*] _expression_]

== DESCRIPTION

*remwharead* saves URIs of things you want to remember in a database along with
 an URI to the archived version, the current date and time, title, description,
 the full text of the page and optional tags.

== OPTIONS

*-t* _tags_, *--tags* _tags_::
Add tags to _URI_, delimited by commas.

*-e* _format_, *--export* _format_::
Export to _format_. Possible values are _csv_ and _asciidoc_. See _FORMATS_.

*-f* _file_, *--file* _file_::
Save output to _file_. Default is stdout.

*-S* _start_,_end_, *--span* _start_,_end_::
Only export entries between and including _start_ and _end_. _start_ and _end_
are date and time representations according to ISO 8601
(YYYY-MM-DDThh:mm:ss). Time zones are ignored.
Example: `--span 2019-01-01,2019-02-10T12:30`.

*-s* _expression_, *--search-tags* _expression_::
Search in tags. Format: _tag1 AND tag2 OR tag3_. See _SEARCH EXPRESSIONS_.

*--search-all* _expression_::
Search in tags, title, description and full text.

*-h*, *--help*::
Show help message.

*-V*, *--version*::
Print version, copyright and license.

== EXAMPLES

.Save a thing into the database, with tags.
====
`remwharead -t tag1,tag2 https://example.com/article.html`
====

.Export all things between and including 2019-04-01 and 2019-05-31 to a file.
====
`remwharead -e asciidoc -f out.adoc -S 2019-04-01,2019-05-31`
====

.Export all things to an HTML file.
====
`remwharead -e asciidoc | asciidoctor --backend=html5 --out-file=out.html -`
====

.Export all things about GRUB the boot-loader, but nothing about caterpillars.
====
`remwharead -e csv -s "grub AND boot"`
====

== FORMATS

=== csv

CSV is short for comma separated values. All fields are quoted and delimited by
commas. Line breaks in the full text are converted to "\n". Our CSV
implementation follows RFC 4180 and the full MIME media type is
`text/csv;charset=utf-8;header=present`.

=== asciidoc

AsciiDoc is a markup language that can be read as plain text or converted to
HTML, PDF and many other formats.

== SEARCH EXPRESSIONS

A search expression is either a single term, or several terms separated by _AND_
or _OR_. _AND_ takes precedence. The expression _Mountain AND Big OR Vegetable_
finds all things that have either Mountain and Big or Vegetable in them. You can
use _||_ instead of _OR_ and _&&_ instead of _AND_. Note that *--search-tags*
only matches whole tags. Pill does not match Pillow.

== PROTOCOL SUPPORT

Since remwharead is built on libcurl, it supports the same protocols. See
*curl*(1), section _DESCRIPTION_. Titles and descriptions are currently only extracted
when using HTTP(S).

== ENVIRONMENT

You can use proxy servers with the same environment variables as curl. See
*curl*(1), section _ENVIRONMENT_.

== FILES

* *Database*: `${XDG_DATA_HOME}/remwharead/database.sqlite`

`${XDG_DATA_HOME}` is usually `~/.local/share`.

== ERROR CODES

[options="header",cols=">,<"]
|==================================================
| Code | Explanation
|    1 | Missing options / Argument not understood.
|    2 | Database connection failed.
|    3 | File could not be opened.
|    4 | Could not fetch URI.
|==================================================

== SEE ALSO

*curl*(1)

== REPORTING BUGS

Bugtracker: https://schlomp.space/tastytea/remwharead/issues

E-mail: tastytea@tastytea.de
